# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-01 19:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Buyers',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('make', models.CharField(max_length=30)),
                ('car_model', models.CharField(max_length=30)),
                ('year', models.IntegerField()),
                ('color', models.CharField(max_length=30)),
                ('body_type', models.CharField(max_length=30)),
                ('num_seats', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sellers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=30)),
                ('day_avail', models.CharField(max_length=30)),
                ('time_avail', models.CharField(max_length=30)),
                ('day_due', models.CharField(max_length=30)),
                ('time_due', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('user_name', models.CharField(max_length=30)),
                ('age', models.IntegerField()),
                ('rating', models.IntegerField()),
            ],
        ),
    ]
