sudo: required

services:
  - docker

before_install:
  - docker pull mysql:5.7.14
  - mkdir -p ~/cs4501
  - mkdir ~/cs4501/db
  - docker run --name mysql -d -e MYSQL\_ROOT\_PASSWORD='$3cureUS' -v ~/cs4501/db:/var/lib/mysql  mysql:5.7.14
  - sleep 15
  - docker run -it --name mysql-cmdline --link mysql:db mysql:5.7.14 mysql -uroot -p'$3cureUS' -h db -e "create user 'www'@'%' identified by '\$3cureUS'; create database cs4501 character set utf8; create database test_cs4501 character set utf8; grant all on cs4501.* to 'www'@'%'; grant all on test_cs4501.* to 'www'@'%';"
  - cd hap
  - docker build -t my-haproxy .
  - cd ..
before_script:
  - docker-compose up -d
  - sleep 10
script:
  - docker ps -a
  - docker exec -it cs4501team4_models_1 bash -c "python ./manage.py test --no-input"