models:
   image: tp33/django
   external_links:
      - mysql:db
   volumes:
      - ./models/:/app
   command: bash -c "python ./manage.py makemigrations models && python ./manage.py migrate && python ./manage.py loaddata db.json && mod_wsgi-express start-server --reload-on-changes ./models/wsgi.py && docker run -it --name web -p 8001:8000"

exp:
   image: tp33/django
   links:
      - models:models-api
      - kafka:kafka
      - es:es
   # ports:
   #    - "8002:8000"
   volumes:
      - ./exp/:/app
   command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"

web1:
   image: tp33/django
   links:
      - exp:exp-api
      - selenium_chrome:selenium_chrome
   ports:
      - "8003:8000"
   volumes:
      - ./web/:/app
   command: bash -c "pip install selenium && pip install requests && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"

web2:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8006:8000"
   volumes:
      - ./web/:/app
   command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"

kafka:
   image: spotify/kafka
   container_name: kafka
   environment:
      ADVERTISED_HOST: kafka
      ADVERTISED_PORT: 9092
   hostname: kafka

es:
   image: elasticsearch:2.0
   container_name: es
   ports:
      - "9200:9200"

batch:
   image: tp33/django
   container_name: batch
   links:
      - kafka:kafka
      - es:es
   volumes:
      - ./:/app
   command: bash -c "python ./search_indexer.py"

load_balancer:
  image: my-haproxy
  container_name: load_balancer
  ports:
    - "8005:8000"
  links:
    - web1:web1
    - web2:web2
    - selenium_chrome:selenium_chrome
  volumes:
    - ./hap/:/haproxy.cfg

selenium_chrome:
  image: selenium/standalone-chrome
  container_name: selenium_chrome
  ports:
    - "4444:4444"

spark-master:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.master.Master -h spark-master
  container_name: spark-master
  hostname: spark-master
  environment:
    MASTER: spark://spark-master:7077
    SPARK_CONF_DIR: /conf
  expose:
    - 7001
    - 7002
    - 7003
    - 7004
    - 7005
    - 7006
    - 7077
    - 6066
  ports:
    - 4040:4040
    - 6066:6066
    - 7077:7077
    - 8082:8080
  volumes:
    - ./data:/app

spark-worker:
  image: gettyimages/spark
  command: bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
  container_name: spark-worker
  hostname: spark-worker
  environment:
    SPARK_CONF_DIR: /conf
    SPARK_WORKER_CORES: 2
    SPARK_WORKER_MEMORY: 512m
    SPARK_WORKER_PORT: 8881
    SPARK_WORKER_WEBUI_PORT: 8081
  links:
    - spark-master
  expose:
    - 7012
    - 7013
    - 7014
    - 7015
    - 7016
    - 8881
  ports:
    - 8081:8081
  volumes:
    - ./data:/app

spark_batch:
   image: tp33/django
   container_name: spark_batch
   links:
      - kafka:kafka
   volumes:
      - ./:/app
   command: bash -c "python ./data/update_log.py"
