models:
   image: tp33/django
   external_links:
      - mysql:db
   ports:
      - "8001:8000"
   volumes:
      - ./models/:/app
   command: bash -c "python ./manage.py makemigrations models && python ./manage.py migrate && python ./manage.py loaddata db.json && mod_wsgi-express start-server --reload-on-changes ./models/wsgi.py && docker run -it --name web -p 8001:8000"

exp:
   image: tp33/django
   links:
      - models:models-api
   ports:
      - "8002:8000"
   volumes:
      - ./exp/:/app
   command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes ./exp/wsgi.py"

web:
   image: tp33/django
   links:
      - exp:exp-api
   ports:
      - "8003:8000"
   volumes:
      - ./web/:/app
   command: bash -c "pip install requests && mod_wsgi-express start-server --reload-on-changes ./web/wsgi.py"